/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Admin_Views;

import Models.Entities.User;
import Utilities.Paths;
import Views.AccountSettingsPanel;
import Views.Login;
import Views.RegisterGeneral;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author hfyh
 */
public class ControlPanel extends javax.swing.JFrame {

    //////////////// TERMINADO CON BDD ////////////////////

    ImageIcon homeUnfocus = new ImageIcon("src\\main\\java\\Images\\home-unfocus.png");
    ImageIcon homeFocus = new ImageIcon("src\\main\\java\\Images\\home-focus.png");
    private User admin;
    
    public ControlPanel() {
        initComponents();
        panelControlContent.setLayout(new BorderLayout());
        setLocationRelativeTo(null);
    }

    public ControlPanel(User admin) {
        this.admin = admin;
        initComponents();
        panelControlContent.setLayout(new BorderLayout());
        setLocationRelativeTo(null);
        logoImage.setIcon(new ImageIcon(Paths.PONY_LOGO));
        btnHome.setIcon(new ImageIcon(Paths.HOME_UNFOCUS));
        btnAccount.setIcon(new ImageIcon(Paths.USER_ICON));
        btnSellers.setIcon(new ImageIcon(Paths.USERS_ICON));
        btnSucursal.setIcon(new ImageIcon(Paths.WORLD));
        btnClients.setIcon(new ImageIcon(Paths.CARRITO));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logoImage = new org.edisoncor.gui.panel.PanelImage();
        btnClients = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnAccount = new javax.swing.JButton();
        btnSellers = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSucursal = new javax.swing.JButton();
        btnNewAdmin = new javax.swing.JButton();
        btnUnlog = new javax.swing.JButton();
        btnSubscriptions = new javax.swing.JButton();
        panelControlContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(245, 245, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout logoImageLayout = new javax.swing.GroupLayout(logoImage);
        logoImage.setLayout(logoImageLayout);
        logoImageLayout.setHorizontalGroup(
            logoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );
        logoImageLayout.setVerticalGroup(
            logoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        btnClients.setBackground(new java.awt.Color(255, 255, 255));
        btnClients.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        btnClients.setForeground(new java.awt.Color(120, 135, 152));
        btnClients.setText("Gestionar clientes");
        btnClients.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClientsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClientsMouseExited(evt);
            }
        });
        btnClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(120, 135, 152));
        jLabel1.setText("Cuentas");

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        btnHome.setForeground(new java.awt.Color(120, 135, 152));
        btnHome.setText("Panel de control");
        btnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
        });
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnAccount.setBackground(new java.awt.Color(255, 255, 255));
        btnAccount.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        btnAccount.setForeground(new java.awt.Color(120, 135, 152));
        btnAccount.setText("Ajustes de cuenta");
        btnAccount.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAccountMouseExited(evt);
            }
        });
        btnAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountActionPerformed(evt);
            }
        });

        btnSellers.setBackground(new java.awt.Color(255, 255, 255));
        btnSellers.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnSellers.setForeground(new java.awt.Color(120, 135, 152));
        btnSellers.setText("Gestionar vendedores");
        btnSellers.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSellers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSellersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSellersMouseExited(evt);
            }
        });
        btnSellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellersActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(120, 135, 152));
        jLabel2.setText("Sucursales");

        btnSucursal.setBackground(new java.awt.Color(255, 255, 255));
        btnSucursal.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        btnSucursal.setForeground(new java.awt.Color(120, 135, 152));
        btnSucursal.setText("Gestionar sucursal");
        btnSucursal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSucursalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSucursalMouseExited(evt);
            }
        });
        btnSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucursalActionPerformed(evt);
            }
        });

        btnNewAdmin.setBackground(new java.awt.Color(102, 153, 255));
        btnNewAdmin.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnNewAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnNewAdmin.setText("Nuevo Admin");
        btnNewAdmin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAdminActionPerformed(evt);
            }
        });

        btnUnlog.setBackground(new java.awt.Color(105, 108, 255));
        btnUnlog.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnUnlog.setForeground(new java.awt.Color(255, 255, 255));
        btnUnlog.setText("Cerrar sesión");
        btnUnlog.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnlogActionPerformed(evt);
            }
        });

        btnSubscriptions.setBackground(new java.awt.Color(255, 255, 255));
        btnSubscriptions.setFont(new java.awt.Font("Roboto Medium", 0, 16)); // NOI18N
        btnSubscriptions.setForeground(new java.awt.Color(120, 135, 152));
        btnSubscriptions.setText("Gestionar suscripciones");
        btnSubscriptions.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSubscriptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubscriptionsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubscriptionsMouseExited(evt);
            }
        });
        btnSubscriptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubscriptionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSellers, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(logoImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(btnSubscriptions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClients, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSellers, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubscriptions, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(btnNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(521, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 700));

        panelControlContent.setBackground(new java.awt.Color(245, 245, 249));

        javax.swing.GroupLayout panelControlContentLayout = new javax.swing.GroupLayout(panelControlContent);
        panelControlContent.setLayout(panelControlContentLayout);
        panelControlContentLayout.setHorizontalGroup(
            panelControlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelControlContentLayout.setVerticalGroup(
            panelControlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        jPanel1.add(panelControlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeFocusGained(JButton btn){
        btn.setBackground(Color.decode("#e7e7ff"));
        btn.setForeground(Color.decode("#6b6eff"));
    }
    private void changeFocusLost(JButton btn){
        btn.setBackground(Color.WHITE);
        btn.setForeground(Color.decode("#788798"));
    }
    
    private void btnClientsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientsMouseEntered
        // TODO add your handling code here:
        changeFocusGained(btnClients);
    }//GEN-LAST:event_btnClientsMouseEntered

    private void btnClientsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClientsMouseExited
        // TODO add your handling code here:
        changeFocusLost(btnClients);
        
    }//GEN-LAST:event_btnClientsMouseExited

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        changeFocusGained(btnHome);
        btnHome.setIcon(homeFocus);
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        changeFocusLost(btnHome);
        btnHome.setIcon(homeUnfocus);
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccountMouseEntered
        // TODO add your handling code here:
        changeFocusGained(btnAccount);
    }//GEN-LAST:event_btnAccountMouseEntered

    private void btnAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccountMouseExited
        // TODO add your handling code here:
        changeFocusLost(btnAccount);
    }//GEN-LAST:event_btnAccountMouseExited

    private void btnSellersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellersMouseEntered
        // TODO add your handling code here:
        changeFocusGained(btnSellers);
    }//GEN-LAST:event_btnSellersMouseEntered

    private void btnSellersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSellersMouseExited
        // TODO add your handling code here:
        changeFocusLost(btnSellers);
    }//GEN-LAST:event_btnSellersMouseExited

    private void btnSucursalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSucursalMouseEntered
        // TODO add your handling code here:
        changeFocusGained(btnSucursal);
    }//GEN-LAST:event_btnSucursalMouseEntered

    private void btnSucursalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSucursalMouseExited
        // TODO add your handling code here:
        changeFocusLost(btnSucursal);
    }//GEN-LAST:event_btnSucursalMouseExited

    private void btnUnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnlogActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnUnlogActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        panelControlContent.removeAll();

        // Añadir el nuevo panel (homePanel)
        panelControlContent.add(new HomeControlPanel(panelControlContent, admin )); // Cambiado a bdd: Listo

        // Actualizar la interfaz gráfica
        panelControlContent.updateUI();
    }//GEN-LAST:event_formWindowOpened

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        panelControlContent.removeAll();

        // Añadir el nuevo panel (homePanel)
        panelControlContent.add(new HomeControlPanel(panelControlContent, admin));

        // Actualizar la interfaz gráfica
        panelControlContent.updateUI();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAdminActionPerformed
        // TODO add your handling code here:
        new RegisterGeneral(admin).setVisible(true); // Cambiado a bdd: Listo
        dispose();
    }//GEN-LAST:event_btnNewAdminActionPerformed

    private void btnSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucursalActionPerformed
        // TODO add your handling code here:
        panelControlContent.removeAll();

        // Añadir el nuevo panel (succursalPanel)
        panelControlContent.add(new SucursalControlPanel(admin)); // Cambiado a bdd: Listo

        // Actualizar la interfaz gráfica
        panelControlContent.updateUI();


    }//GEN-LAST:event_btnSucursalActionPerformed

    private void btnSellersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellersActionPerformed
        // TODO add your handling code here:
        panelControlContent.removeAll();

        // Añadir el nuevo panel (succursalPanel)
        panelControlContent.add(new SellerControlPanel(admin)); // Cambiado a bdd: Listo

        // Actualizar la interfaz gráfica
        panelControlContent.updateUI();

    }//GEN-LAST:event_btnSellersActionPerformed

    private void btnClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientsActionPerformed
        // TODO add your handling code here:
        panelControlContent.removeAll();

        // Añadir el nuevo panel (succursalPanel)
        panelControlContent.add(new ClientControlPanel(admin)); // Cambiado a bdd: Listo

        // Actualizar la interfaz gráfica
        panelControlContent.updateUI();
    }//GEN-LAST:event_btnClientsActionPerformed

    private void btnAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountActionPerformed
        // TODO add your handling code here:
        panelControlContent.removeAll();

        // Añadir el nuevo panel (succursalPanel)
        panelControlContent.add(new AccountSettingsPanel(admin)); // Cambiado a bdd: Listo

        // Actualizar la interfaz gráfica
        panelControlContent.updateUI();
        
        
    }//GEN-LAST:event_btnAccountActionPerformed

    private void btnSubscriptionsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubscriptionsMouseEntered
        // TODO add your handling code here:
        changeFocusGained(btnSubscriptions);
    }//GEN-LAST:event_btnSubscriptionsMouseEntered

    private void btnSubscriptionsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubscriptionsMouseExited
        // TODO add your handling code here:
        changeFocusLost(btnSubscriptions);
    }//GEN-LAST:event_btnSubscriptionsMouseExited

    private void btnSubscriptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubscriptionsActionPerformed
        // TODO add your handling code here:
        panelControlContent.removeAll();

        // Añadir el nuevo panel (succursalPanel)
        panelControlContent.add(new SubscriptionControlPanel(admin)); // Cambiado a bdd: Listo

        // Actualizar la interfaz gráfica
        panelControlContent.updateUI();
    }//GEN-LAST:event_btnSubscriptionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccount;
    private javax.swing.JButton btnClients;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnNewAdmin;
    private javax.swing.JButton btnSellers;
    private javax.swing.JButton btnSubscriptions;
    private javax.swing.JButton btnSucursal;
    private javax.swing.JButton btnUnlog;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.panel.PanelImage logoImage;
    private javax.swing.JPanel panelControlContent;
    // End of variables declaration//GEN-END:variables
}
