/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Admin_Views;

import Models.Entities.SubscriptionPlan;
import Models.Entities.Sucursal;
import Models.Entities.User;
import static Utilities.Paths.SUCURSAL_FILE;
import static Utilities.Paths.SUBSCRIPTION_PLAN_FILE;

import Models.ModelSubscriptionPlan;
import Models.ModelSucursal;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.awt.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JESUS
 */
public class SubscriptionControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form SubscriptionControlPanel
     */
    private ArrayList<SubscriptionPlan> subscriptions = new ArrayList<SubscriptionPlan>();
    private ArrayList<Sucursal> sucursales = new ArrayList<Sucursal>();
    private User admin;
    private final ModelSucursal modelSucursal = new ModelSucursal();
    private final ModelSubscriptionPlan modelSubscriptionPlan = new ModelSubscriptionPlan();
    
    public SubscriptionControlPanel() {
        initComponents();
        readSubscriptions();
        readSucursales();
    }
    public SubscriptionControlPanel(User admin) {
        this.admin = admin;
        initComponents();
        readSubscriptions();
        readSucursales();
    }
    
    private void readSubscriptions(){
        subscriptions.clear();

        try {
            subscriptions = modelSubscriptionPlan.getAll();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            for(SubscriptionPlan subscription : subscriptions){

                String estado = "";
                if(subscription.isStatus()){
                    estado = "Activa";
                } else{
                    estado = "Inactiva";
                }
                
                model.addRow(new Object[]{subscription.getIdSubscriptionPlan(), subscription.getTitle(),
                    subscription.getDescription(), subscription.getPrice(), estado});
                
            }
            jTable1.setModel(model);
            jTable1.updateUI();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void addSubscription(SubscriptionPlan subscription){
        try {
            modelSubscriptionPlan.add(subscription);
            readSubscriptions();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void readSucursales(){
        sucursales.clear();
        sucursalSelector.removeAll();
        try {
            sucursales = modelSucursal.getActives();

            for(Sucursal sucursal : sucursales){
                sucursalSelector.addItem(sucursal);
                
            }
            sucursalSelector.updateUI();


        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDeleteSucursal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldTitle = new javax.swing.JTextField();
        fieldDescription = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldPrice = new javax.swing.JSpinner();
        btnAddSucursal1 = new javax.swing.JButton();
        btnChangeStatus = new javax.swing.JButton();
        sucursalSelector = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(245, 245, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Suscripcion", "Titulo", "Descripción", "Precio", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 740, 465));

        btnDeleteSucursal.setBackground(new java.awt.Color(255, 51, 0));
        btnDeleteSucursal.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnDeleteSucursal.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteSucursal.setText("Eliminar");
        btnDeleteSucursal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDeleteSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 620, 180, 20));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Titulo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 180, -1));

        fieldTitle.setBackground(new java.awt.Color(255, 255, 255));
        fieldTitle.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldTitle.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(fieldTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 180, 30));

        fieldDescription.setBackground(new java.awt.Color(255, 255, 255));
        fieldDescription.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldDescription.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(fieldDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 180, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Escoge sucursal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 180, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Precio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 180, -1));

        fieldPrice.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldPrice.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, null, 15.0d));
        fieldPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldPrice.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fieldPricePropertyChange(evt);
            }
        });
        jPanel1.add(fieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 180, 30));

        btnAddSucursal1.setBackground(new java.awt.Color(105, 108, 255));
        btnAddSucursal1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAddSucursal1.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSucursal1.setText("Añadir suscripción");
        btnAddSucursal1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAddSucursal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSucursal1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddSucursal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 180, 40));

        btnChangeStatus.setBackground(new java.awt.Color(0, 255, 51));
        btnChangeStatus.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnChangeStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeStatus.setText("Cambiar estado");
        btnChangeStatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStatusActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangeStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 600, 180, 20));

        jPanel1.add(sucursalSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 180, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Descripción");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 180, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSucursalActionPerformed
        // TODO add your handling code here:
        try {
            SubscriptionPlan subscription = selectedSubscription();
            if(modelSubscriptionPlan.delete(subscription.getIdSubscriptionPlan())){
                JOptionPane.showMessageDialog(null,"Suscripción eliminada.");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnDeleteSucursalActionPerformed

    private void fieldPricePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fieldPricePropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fieldPricePropertyChange

    private void btnAddSucursal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSucursal1ActionPerformed
        // TODO add your handling code here:
        try {
            String title = fieldTitle.getText();
            String description = fieldDescription.getText();
            Double price = (double) fieldPrice.getValue();
            Sucursal sucursal = (Sucursal) sucursalSelector.getSelectedItem();
            Integer idSucursal = sucursal.getIdSucursal();

            if(title.isEmpty() || description.isEmpty()){
                return;
            }

            SubscriptionPlan subscription = new SubscriptionPlan(null, price, title, description, idSucursal, true);
            addSubscription(subscription);
            fieldTitle.setText("");
            fieldDescription.setText("");
            fieldPrice.setValue(1.0);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddSucursal1ActionPerformed

    private void btnChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStatusActionPerformed
        // TODO add your handling code here:

        try {
            SubscriptionPlan subscription = selectedSubscription();
            subscription.setStatus(!subscription.isStatus());
            modelSubscriptionPlan.update(subscription);
            readSubscriptions();
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnChangeStatusActionPerformed

    private SubscriptionPlan selectedSubscription(){
        try {
            int indice = jTable1.getSelectedRow();
            if(indice<0){
                return null;
            }
            int idSubscription =  (int)jTable1.getValueAt(indice, 0);
            SubscriptionPlan subscription = modelSubscriptionPlan.byId(idSubscription);

            return subscription;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSucursal1;
    private javax.swing.JButton btnChangeStatus;
    private javax.swing.JButton btnDeleteSucursal;
    private javax.swing.JTextField fieldDescription;
    private javax.swing.JSpinner fieldPrice;
    private javax.swing.JTextField fieldTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<Sucursal> sucursalSelector;
    // End of variables declaration//GEN-END:variables
}
