/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views.Admin_Views;

import Models.Entities.Sucursal;
import Models.Entities.User;
import Models.ModelSucursal;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.ArrayList;

import static Utilities.Paths.SUCURSAL_FILE;

/**
 *
 * @author hfyh
 */
public class SucursalControlPanel extends javax.swing.JPanel {
    
    private ArrayList<Sucursal> sucursales = new ArrayList<Sucursal>();
    private User admin;
    private ModelSucursal modelSucursal = new ModelSucursal();
    /**
     * Creates new form SucursalControlPanel
     */
    public SucursalControlPanel() {
        initComponents();
    }
    
    public SucursalControlPanel(User admin) {
        this.admin = admin;
        initComponents();
        readSucursales();
    }


    private void readSucursales(){
        sucursales.clear();

        try {
            sucursales = modelSucursal.getAll();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            for(Sucursal sucursal : sucursales){
                String estado = "";
                if(sucursal.isStatus()){
                    estado = "Activa";
                } else{
                    estado = "Inactiva";
                }
                
                model.addRow(new Object[]{sucursal.getIdSucursal(), sucursal.getNombre(), sucursal.getDireccion(), sucursal.getTelefono(), estado});
                jTable1.setModel(model);
                jTable1.updateUI();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void addSucursal(Sucursal sucursal){
        try {
            modelSucursal.addSucursal(sucursal);
            JOptionPane.showMessageDialog(null, "Sucursal añadida: "+sucursal.getNombre());
            readSucursales();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnDeleteSucursal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        fieldAdress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldGainsSucursal = new javax.swing.JSpinner();
        btnAddSucursal1 = new javax.swing.JButton();
        btnChangeStatus = new javax.swing.JButton();

        setBackground(new java.awt.Color(245, 245, 249));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Sucursal", "Nombre", "Dirección", "Número", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 740, 465));

        btnDeleteSucursal.setBackground(new java.awt.Color(255, 51, 0));
        btnDeleteSucursal.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnDeleteSucursal.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteSucursal.setText("Eliminar");
        btnDeleteSucursal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDeleteSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSucursalActionPerformed(evt);
            }
        });
        add(btnDeleteSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 630, 180, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nombre sucursal");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 180, -1));

        fieldName.setBackground(new java.awt.Color(255, 255, 255));
        fieldName.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldName.setForeground(new java.awt.Color(0, 0, 0));
        add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 180, 30));

        fieldAdress.setBackground(new java.awt.Color(255, 255, 255));
        fieldAdress.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldAdress.setForeground(new java.awt.Color(0, 0, 0));
        add(fieldAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 530, 180, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dirección");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, 180, -1));

        fieldPhone.setBackground(new java.awt.Color(255, 255, 255));
        fieldPhone.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldPhone.setForeground(new java.awt.Color(0, 0, 0));
        add(fieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 180, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Telefono");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 180, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("% Ganancia sucursal");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 180, -1));

        fieldGainsSucursal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldGainsSucursal.setModel(new javax.swing.SpinnerNumberModel(1.0d, 0.0d, 100.0d, 5.0d));
        fieldGainsSucursal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        fieldGainsSucursal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fieldGainsSucursalPropertyChange(evt);
            }
        });
        add(fieldGainsSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 180, 30));

        btnAddSucursal1.setBackground(new java.awt.Color(105, 108, 255));
        btnAddSucursal1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAddSucursal1.setForeground(new java.awt.Color(255, 255, 255));
        btnAddSucursal1.setText("Añadir sucursal");
        btnAddSucursal1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAddSucursal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddSucursal1ActionPerformed(evt);
            }
        });
        add(btnAddSucursal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 180, 40));

        btnChangeStatus.setBackground(new java.awt.Color(0, 255, 51));
        btnChangeStatus.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnChangeStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeStatus.setText("Cambiar estado");
        btnChangeStatus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnChangeStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeStatusActionPerformed(evt);
            }
        });
        add(btnChangeStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 590, 180, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSucursalActionPerformed
        // TODO add your handling code here:
        try {
            modelSucursal.deleteSucursal(selectedSucursal());
            JOptionPane.showMessageDialog(null, "Eliminacion de la sucursal: "+selectedSucursal());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteSucursalActionPerformed

    private void fieldGainsSucursalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fieldGainsSucursalPropertyChange
        // TODO add your handling code here:
        if ((double) fieldGainsSucursal.getValue() > 100.0) {
            fieldGainsSucursal.setValue(100);
        }
    }//GEN-LAST:event_fieldGainsSucursalPropertyChange

    private void btnAddSucursal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddSucursal1ActionPerformed
        // TODO add your handling code here:
        String name = fieldName.getText();
        String adress = fieldAdress.getText();
        String phone = fieldPhone.getText();
        Double gananciaSucursal = (double) fieldGainsSucursal.getValue();
        Double gananciaAdmin = 100 - gananciaSucursal;
        if(name.isEmpty() || adress.isEmpty() || phone.isEmpty()){
            return;
        }
        Sucursal sucursal = new Sucursal(null, name, adress,gananciaAdmin, gananciaSucursal, phone, true);
        addSucursal(sucursal);
        fieldName.setText("");
        fieldAdress.setText("");
        fieldPhone.setText("");
        fieldGainsSucursal.setValue(1.0);
    }//GEN-LAST:event_btnAddSucursal1ActionPerformed

    private void btnChangeStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeStatusActionPerformed
        // TODO add your handling code here:

        Sucursal sucursal = null;
        try {
            sucursal = modelSucursal.byId(selectedSucursal());
            sucursal.setStatus(!sucursal.isStatus());
            modelSucursal.updateSucursal(sucursal);
            readSucursales();
            JOptionPane.showMessageDialog(null, "Estado cambiado de la sucursal: "+sucursal.getNombre());
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnChangeStatusActionPerformed

    /////////////////////////
    

    private Integer selectedSucursal(){

        int indice = jTable1.getSelectedRow();
        if(indice<0){
            return null;
        }
        int idSucursal =  (int)jTable1.getValueAt(indice, 0);

        
        return idSucursal;
    }





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSucursal1;
    private javax.swing.JButton btnChangeStatus;
    private javax.swing.JButton btnDeleteSucursal;
    private javax.swing.JTextField fieldAdress;
    private javax.swing.JSpinner fieldGainsSucursal;
    private javax.swing.JTextField fieldName;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
