/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;

import Models.Entities.Sucursal;
import Models.Entities.User;
import Models.ModelSucursal;
import Models.ModelUser;
import Utilities.Authentication;
import Utilities.Paths;
import static Utilities.Paths.USER_FILE;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author hfyh
 */
public class AccountSettingsPanel extends javax.swing.JPanel {

    /**
     * Creates new form AccountSettingsPanel
     */
    private User admin;
    private ModelSucursal modelSucursal = new ModelSucursal();
    private ModelUser modelUser = new ModelUser();
    
    public AccountSettingsPanel() {
        initComponents();
        panelImage1.setIcon(new ImageIcon(Paths.PONY_LOGO));
        lblError.setVisible(false);
    }
    
    public AccountSettingsPanel(User admin) {
        this.admin = admin;
        initComponents();
        panelImage1.setIcon(new ImageIcon(Paths.PONY_LOGO));
        lblError.setVisible(false);
        setFields(admin);
    }

    private void updateUsers(User usr){
        try {
            modelUser.update(usr);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void setFields(User admin){
        this.admin = admin;
        fieldName.setText(admin.getName());
        fieldUsername.setText(admin.getUsername());
        fieldEmail.setText(admin.getEmail());
        fieldPhone.setText(admin.getPhone());
        updateUI();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        fieldPassword = new javax.swing.JPasswordField();
        btnTheme = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fieldUsername = new javax.swing.JTextField();
        fieldEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldPhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblError = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fieldRepeatPassword = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        fieldNewPassword = new javax.swing.JPasswordField();

        jPanel1.setBackground(new java.awt.Color(245, 245, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 250, 250));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 180, -1));

        fieldName.setBackground(new java.awt.Color(255, 255, 255));
        fieldName.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldName.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 180, 30));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Contraseña");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 170, -1));

        btnUpdate.setBackground(new java.awt.Color(51, 51, 255));
        btnUpdate.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Actualizar");
        btnUpdate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 600, 120, 40));

        fieldPassword.setBackground(new java.awt.Color(255, 255, 255));
        fieldPassword.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldPassword.setForeground(new java.awt.Color(0, 0, 0));
        fieldPassword.setToolTipText("");
        jPanel1.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 190, 30));

        btnTheme.setBackground(new java.awt.Color(245, 245, 249));
        btnTheme.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemeActionPerformed(evt);
            }
        });
        jPanel1.add(btnTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 40, 40));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre de usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 180, -1));

        fieldUsername.setBackground(new java.awt.Color(255, 255, 255));
        fieldUsername.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldUsername.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, 180, 30));

        fieldEmail.setBackground(new java.awt.Color(255, 255, 255));
        fieldEmail.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldEmail.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(fieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 180, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 190, -1));

        fieldPhone.setBackground(new java.awt.Color(255, 255, 255));
        fieldPhone.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldPhone.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(fieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 190, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Email");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 180, -1));

        lblError.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        lblError.setForeground(new java.awt.Color(204, 0, 51));
        lblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblError.setText("Error: Llene todos los campos necesarios");
        jPanel1.add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 430, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Repetir contraseña");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 190, -1));

        fieldRepeatPassword.setBackground(new java.awt.Color(255, 255, 255));
        fieldRepeatPassword.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldRepeatPassword.setForeground(new java.awt.Color(0, 0, 0));
        fieldRepeatPassword.setToolTipText("");
        jPanel1.add(fieldRepeatPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 190, 30));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Nueva contraseña");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 160, -1));

        fieldNewPassword.setBackground(new java.awt.Color(255, 255, 255));
        fieldNewPassword.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldNewPassword.setForeground(new java.awt.Color(0, 0, 0));
        fieldNewPassword.setToolTipText("");
        jPanel1.add(fieldNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        User user = admin;


        String name = fieldName.getText();
        String username = fieldUsername.getText();
        String password = new String(fieldPassword.getPassword());
        String newPassword = new String(fieldNewPassword.getPassword());
        boolean passwordMatchOld = Authentication.verifyPassword(password, user.getPassword());
        String repeatPassword = new String(fieldRepeatPassword.getPassword());
        boolean passwordMatch = newPassword.equals(repeatPassword);
        String phone = fieldPhone.getText();
        String email = fieldEmail.getText();

        System.out.println("User Password: " + user.getPassword());
        System.out.println("Password: " + password);
        System.out.println("New Password: " + newPassword);
        System.out.println("Repeat Password: " + repeatPassword);
        System.out.println("Password Match: " + passwordMatch);
        System.out.println("Password Match Old: " + passwordMatchOld);

        if (!passwordMatch) {
            lblError.setText("Error: Las contraseñas no coinciden");
            lblError.setVisible(true);
            return;
        }
        if(newPassword.isEmpty() || repeatPassword.isEmpty() || password.isEmpty() || name.isEmpty() || username.isEmpty() || email.isEmpty() || phone.isEmpty()){
            lblError.setText("Error: Llene todos los campos necesarios");
            lblError.setVisible(true);
            return;
        }
        if(!passwordMatchOld){
            lblError.setText("Error: Contraseña incorrecta");
            lblError.setVisible(true);
            return;
        }

        user.setName(fieldName.getText());
        user.setUsername(fieldUsername.getText());
        user.setEmail(fieldEmail.getText());
        user.setPhone(fieldPhone.getText());
        user.setPassword(newPassword);
        updateUsers(user);
        this.admin = user;
        setFields(this.admin);
        lblError.setVisible(false);


    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemeActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnThemeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTheme;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldName;
    private javax.swing.JPasswordField fieldNewPassword;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JPasswordField fieldRepeatPassword;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblError;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
