/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Views.Admin_Views.ControlPanel;
import Models.Entities.User;
import Models.ModelUser;
import Utilities.Authentication;
import Utilities.Paths;
import Views.Client_Views.ControlPanelClients;
import Views.Seller_Views.SellerControlFrame;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import javax.swing.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;

import static Utilities.Paths.USER_FILE;

/**
 *
 * @author hfyh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */


    private int actualTheme = 0;
    
    public Login() {
        
        if(actualTheme == 1){
            FlatLightLaf.setup();
        } else if(actualTheme == 0){
            FlatDarkLaf.setup();
        }
        
        initComponents();
        panelErrorMessage.setVisible(false);
        panelImage1.setIcon(new ImageIcon(Paths.PONY_LOGO));
        btnClearUsername.setIcon(new ImageIcon(Paths.EQUIS));
        btnClearPassword.setIcon(new ImageIcon(Paths.EQUIS));
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        btnRegister = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnClearPassword = new javax.swing.JButton();
        btnClearUsername = new javax.swing.JButton();
        btnTheme = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        fieldUsername = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        panelErrorMessage = new javax.swing.JPanel();
        lblErrorMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(245, 245, 249));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelImage1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JESUS\\Documents\\Uni\\proyectoSuscripcionesJAVA\\src\\main\\java\\Images\\PonyFood.png")); // NOI18N

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        jPanel1.add(panelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 250, 250));

        btnRegister.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnRegister.setText("Registrar");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 120, 40));

        btnLogin.setBackground(new java.awt.Color(51, 102, 255));
        btnLogin.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Iniciar sesión");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 102, 255), 1, true));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 120, 40));

        btnClearPassword.setBackground(new java.awt.Color(245, 245, 249));
        btnClearPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClearPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btnClearPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 40, 40));

        btnClearUsername.setBackground(new java.awt.Color(245, 245, 249));
        btnClearUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnClearUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(btnClearUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 40, 40));

        btnTheme.setBackground(new java.awt.Color(245, 245, 249));
        btnTheme.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTheme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemeActionPerformed(evt);
            }
        });
        jPanel1.add(btnTheme, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 40, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fieldUsername.setBackground(new java.awt.Color(255, 255, 255));
        fieldUsername.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldUsername.setForeground(new java.awt.Color(0, 0, 0));
        fieldUsername.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        fieldUsername.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel2.add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 280, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Usuario");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 300, 60));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Contraseña");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 280, 30));

        fieldPassword.setBackground(new java.awt.Color(255, 255, 255));
        fieldPassword.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        fieldPassword.setForeground(new java.awt.Color(0, 0, 0));
        fieldPassword.setToolTipText("");
        fieldPassword.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 280, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 300, 60));

        panelErrorMessage.setBackground(new java.awt.Color(255, 102, 102));
        panelErrorMessage.setEnabled(false);

        lblErrorMessage.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorMessage.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        lblErrorMessage.setForeground(new java.awt.Color(51, 51, 51));
        lblErrorMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblErrorMessage.setText("Ingrese todos los datos");

        javax.swing.GroupLayout panelErrorMessageLayout = new javax.swing.GroupLayout(panelErrorMessage);
        panelErrorMessage.setLayout(panelErrorMessageLayout);
        panelErrorMessageLayout.setHorizontalGroup(
            panelErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
        panelErrorMessageLayout.setVerticalGroup(
            panelErrorMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(panelErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 300, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearUsernameActionPerformed
        // TODO add your handling code here:
        fieldUsername.setText("");
    }//GEN-LAST:event_btnClearUsernameActionPerformed

    private void btnClearPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearPasswordActionPerformed
        // TODO add your handling code here:
        fieldPassword.setText("");
    }//GEN-LAST:event_btnClearPasswordActionPerformed

    private void btnThemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemeActionPerformed
        // TODO add your handling code here:
        /*if( actualTheme == 1){
            actualTheme = 0;
            FlatDarkLaf.setup();
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        } else if (actualTheme == 0){
            actualTheme = 1;
            FlatLightLaf.setup();
            SwingUtilities.updateComponentTreeUI(this);
            this.pack();
        }*/
    }//GEN-LAST:event_btnThemeActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try {
            String username = fieldUsername.getText();
            String password = new String(fieldPassword.getPassword());


            if(username.isEmpty() || password.isEmpty()){
                lblErrorMessage.setText("Ingrese todos los datos");
                panelErrorMessage.setVisible(true);
            } else{
                panelErrorMessage.setVisible(false);
                System.out.println("Username: " + username);
                System.out.println("Password: " + password);
                User user = null;
                user = new ModelUser().login(username, password);
                if(user != null){
                    if(user.getUser_type() == 1){
                        new ControlPanel(user).setVisible(true);
                        dispose();
                    } else if(user.getUser_type() == 2){
                        new ControlPanelClients(user).setVisible(true);
                        dispose();
                    } else if(user.getUser_type() == 3){
                        new SellerControlFrame(user).setVisible(true);
                        dispose();
                    }
                } else{
                    lblErrorMessage.setText("Usuario o contraseña incorrectos");
                    panelErrorMessage.setVisible(true);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearPassword;
    private javax.swing.JButton btnClearUsername;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnTheme;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblErrorMessage;
    private javax.swing.JPanel panelErrorMessage;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
